---

- name: Gather distribution info
  setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Gather the package facts before prelim
  package_facts:
      manager: auto
  tags:
      - always

- name: Include prelim tasks
  import_tasks: prelim.yml
  tags:
      - prelim_tasks

- name: Gather the package facts after prelim
  package_facts:
      manager: auto
  tags:
      - always

- name: Include CAT I patches
  import_tasks: fix-cat1.yml
  when: ubtu20stig_cat1_patch
  tags:
      - cat1
      - high

- name: Include CAT II patches
  import_tasks: fix-cat2.yml
  when: ubtu20stig_cat2_patch
  tags:
      - cat2
      - medium

- name: Include CAT III patches
  import_tasks: fix-cat3.yml
  when: ubtu20stig_cat3_patch
  tags:
      - cat3
      - low

- name: Flush handlers
  meta: flush_handlers

- name: Reboot system
  block:
      - name: reboot system if not skipped
        reboot:
        when:
            - not ubtu20_skip_reboot

      - name: Warning a reboot required but skip option set
        debug:
            msg: "Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results"
        changed_when: true
        when:
            - ubtu20_skip_reboot

- name: If Warnings found Output count and control IDs affected
  debug:
      msg:
          - "You have {{ warn_count }} Warning(s) that require investigation(s). Their ID’s are listed below:"
          - "{{ warn_control_list }}"
  when: warn_count != 0
