---
- hosts: ansible1
  connection: local
  tasks:
    - name: Load AWS vars
      ansible.builtin.include_vars: ../../vars/aws/gen_certs_password.yml
      when: ansible_system_vendor == 'Amazon EC2'

- hosts: ansible1
  vars:
    ansible_user: "svc_ansible"
    ansible_password: "{{ hostvars['ansible1']['svc_ansible_password'] }}"
    app_name: esdata
    app_path: elastic
    private_key_cipher: auto
    instance_count: 3
    extended_key_usage:
      - serverAuth
      - clientAuth
  roles:
    - gen_tls_cert

- hosts: ansible1
  vars:
    ansible_user: "svc_ansible"
    ansible_password: "{{ hostvars['ansible1']['svc_ansible_password'] }}"
    app_name: esingest
    app_path: elastic
    private_key_cipher: auto
    instance_count: 2
    extended_key_usage:
      - serverAuth
      - clientAuth
    create_unencrypted: true
  roles:
    - gen_tls_cert

- hosts: ansible1
  vars:
    ansible_user: "svc_ansible"
    ansible_password: "{{ hostvars['ansible1']['svc_ansible_password'] }}"
    app_name: kibana
    app_path: elastic
    private_key_cipher: auto
    instance_count: 2
    create_unencrypted: true
  roles:
    - gen_tls_cert
