---

- name: "3.5.3.1.1 | PATCH | Ensure iptables packages are installed"
  package:
      name: "{{ item }}"
      state: present
  with_items:
      - iptables
      - iptables-services
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amazon2cis_rule_3_5_3_1_1
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.3.1
      - firewall
      - iptables

- name: "3.5.3.1.2 | PATCH | Ensure nftables is not installed with iptables"
  package:
      name: nftables
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amazon2cis_rule_3_5_3_1_2
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.3.2
      - firewall
      - iptables

- name: "AUTOMATED | 3.5.3.1.3 | PATCH | Ensure firewalld is either not installed or masked with iptables"
  package:
      name: firewalld
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amazon2cis_rule_3_5_3_1_3
  tags:
      - level1
      - automated
      - patch
      - rule_3.5.3.3
      - firewall
      - iptables
