---

- name: "5.6 | AUDIT | Ensure root login is restricted to system console "
  block:
      - name: "5.6 | AUDIT | Ensure root login is restricted to system console"
        command: cat /etc/securetty
        changed_when: false
        failed_when: false
        register: amazon2_5_6_audit

      - name: "5.6 | AUDIT | Ensure root login is restricted to system console"
        debug:
            msg:
                - "These are the consoles with root login access, please review:"
                - "{{ amazon2_5_6_audit.stdout_lines }}"
  when:
      - amazon2cis_rule_5_6
  tags:
      - level1
      - manual
      - audit
      - rule_5.6
      - accounts
      - root
