---

- name: "5.7 | PATCH | Ensure access to the su command is restricted"
  block:
      - name: "5.7 | PATCH | Ensure access to the su command is restricted | Setting pam_wheel to use_uid"
        lineinfile:
            path: /etc/pam.d/su
            regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
            line: 'auth            required        pam_wheel.so use_uid {% if amazon2cis_sugroup is defined %}group={{ amazon2cis_sugroup }}{% endif %}'

      - name: "5.7 | PATCH | Ensure access to the su command is restricted | wheel group contains root"
        user:
            name: root
            groups: "{{ amazon2cis_sugroup | default('wheel') }}"
  when:
      - amazon2cis_rule_5_7
  tags:
      - level1
      - automated
      - patch
      - rule_5.7
      - sudo
