---

- name: "5.2.1 | PATCH | Ensure sudo is installed"
  package:
      name: sudo
      state: present
  when:
      - amazon2cis_rule_5_2_1
  tags:
      - level1
      - automated
      - patch
      - rule_5.2.1
      - sudo

- name: "5.2.2 | PATCH | Ensure sudo commands use pty"
  lineinfile:
      path: /etc/sudoers
      line: 'Defaults use_pty'
  when:
      - amazon2cis_rule_5_2_2
  tags:
      - level1
      - automated
      - patch
      - rule_5.2.2
      - sudo

- name: "5.2.3 | PATCH | Ensure sudo log file exists"
  lineinfile:
      path: /etc/sudoers
      line: 'Defaults logfile="/var/log/sudo.log"'
  when:
      - amazon2cis_rule_5_2_3
  tags:
      - level1
      - automated
      - patch
      - rule_5.2.3
      - sudo
