---
- hosts: ansible1
  connection: local
  tasks:
    - name: Load AWS vars
      ansible.builtin.include_vars: ../../vars/aws/dc_vars.yml
      when: ansible_system_vendor == 'Amazon EC2'

- hosts: dc1
  vars:
    ansible_user: "svc_ansible_da"
    ansible_password: "{{ hostvars['ansible1']['svc_ansible_da_password'] }}"
  roles:
    - audit/ad_users_and_groups
