---
- name: "MANUAL | 3.1.1 | PATCH | Disable IPv6"
  lineinfile:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=.*(?!.*ipv6\.disable=1)\"[^\"]+)(\".*)'
      line: '\1 ipv6.disable=1\2'
      backrefs: true
  notify: grub update
  when:
      - ubtu18cis_rule_3_1_1
      - not ubtu18cis_ipv6_required
  tags:
      - level2-server
      - level2-workstation
      - manual
      - patch
      - rule_3.1.1
      - ipv6

- name: "AUTOMATED | 3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  block:
      - name: "AUTOMATED | 3.1.2 | AUDIT | Ensure wireless interfaces are disabled | Check if nmcli command is available"
        command: dpkg -s network-manager
        changed_when: false
        failed_when: false
        args:
            warn: false
        check_mode: false
        register: ubtu18cis_nmcli_available


      - name: "AUTOMATED | 3.1.2 | AUDIT | Ensure wireless interfaces are disabled | Check if wifi is enabled"
        command: nmcli radio wifi
        register: ubtu18cis_wifi_enabled
        check_mode: false
        changed_when: ubtu18cis_wifi_enabled.stdout != "disabled"
        when: ubtu18cis_nmcli_available.rc == 0

      - name: "AUTOMATED | 3.1.2 | PATCH | Ensure wireless interfaces are disabled | Disable wifi if enabled"
        command: nmcli radio wifi off
        when: ubtu18cis_wifi_enabled is changed
  when:
      - ubtu18cis_rule_3_1_2
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_3.1.2
      - wireless
