---
- name: "Check to see the current status of FIPS mode"
  command: /usr/bin/fips-mode-setup --check
  register: is_fips_enabled
  changed_when: false
  when:
    - enable_fips
  tags:
    - level1-server
    - level1-workstation
    - level2-server
    - level2-workstation
    - patch
    - fips

- name: "Enable FIPS mode"
  command: /usr/bin/fips-mode-setup --enable
  when:
    - enable_fips
    - is_fips_enabled.stdout.find('FIPS mode is enabled.') == -1
  tags:
    - level1-server
    - level1-workstation
    - level2-server
    - level2-workstation
    - patch
    - fips

- name: "Ensure FIPS SSH Ciphers in RHEL 8"
  lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "(?i)^#?Ciphers"
      line: Ciphers aes256-ctr,aes192-ctr,aes128-ctr
      validate: /usr/sbin/sshd -t -f %s
  #notify: restart sshd
  when:
    - enable_fips
    - is_fips_enabled.stdout.find('FIPS mode is enabled.') == -1
  tags:
    - level1-server
    - level1-workstation
    - level2-server
    - level2-workstation
    - patch
    - fips

- name: "Ensure FIPS SSH MACS in RHEL 8"
  lineinfile:
      create: yes
      dest: /etc/ssh/sshd_config
      regexp: "(?i)^#?MACs"
      line: MACs hmac-sha2-512,hmac-sha2-256
      validate: /usr/sbin/sshd -t -f %s
  #notify: restart sshd
  when:
    - enable_fips
    - is_fips_enabled.stdout.find('FIPS mode is enabled.') == -1
  tags:
    - level1-server
    - level1-workstation
    - level2-server
    - level2-workstation
    - patch
    - fips