---
- name: "AUTOMATED | 4.4 | PATCH | Ensure logrotate assigns appropriate permissions"
  lineinfile:
      path: /etc/logrotate.conf
      regex: '^create'
      line: 'create 0640 root utmp'
  when:
      - ubtu18cis_rule_4_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.4
      - logrotate
