---
collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.windows
  - name: ansible.utils
  - name: community.aws
  - name: community.crypto
  - name: community.postgresql
  - name: community.windows
  - name: microsoft.ad
