---
- name: 1.1.1 | AUDIT | Ensure a separate partition for containers has been created
  ansible.builtin.fail:
    msg: No mount found at /var/lib/docker
  when: ansible_mounts | selectattr('mount', 'equalto', '/var/lib/docker') | list | length == 0

- name: 1.1.2 | AUDIT | Ensure only trusted users are allowed to control Docker daemon
  ansible.builtin.command:
    cmd: getent group docker
  register: docker_group_members

- name: 1.1.2 | AUDIT | Ensure only trusted users are allowed to control Docker daemon
  ansible.builtin.debug:
    var: docker_group_members

- name: 1.1.3 - 1.1.18 | PATCH | Ensure auditing is configured for Docker files and directories
  template:
      src: 99_docker_auditd.rules.j2
      dest: /etc/audit/rules.d/99_docker_auditd.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd