---
galaxy_info:
    author: "Sam Doran, Josh Springer, Daniel Shepherd, James Cassell, Mike Renfro, DFed, George Nalen, Mark Bolwell"
    description: "Apply the DISA RHEL 8 STIG"
    company: "MindPoint Group"
    license: MIT
    role_name: rhel8_stig
    namespace: mindpointgroup
    min_ansible_version: '2.9.0'
    platforms:
        - name: EL
          versions:
              - '8'
    galaxy_tags:
        - system
        - security
        - stig
        - hardening
        - benchmark
        - compliance
        - redhat
        - complianceascode
        - disa
        - rhel8
        - mindpoint
collections:
    - community.general
    - community.crypto
    - ansible.posix
dependencies: []
