---
- hosts: ansible1
  connection: local
  tasks:
    - name: Load AWS vars
      ansible.builtin.include_vars: ../../vars/aws/common.yml
      when: ansible_system_vendor == 'Amazon EC2'

# Note: Assumes that everything that needs to be configured here is done through API calls
- hosts: ansible1
  connection: local
  any_errors_fatal: true
  vars:
    ansible_user: "svc_ansible"
    ansible_password: "{{ hostvars['ansible1']['svc_ansible_password'] }}"
    ansible_sudo_pass: "{{ hostvars['ansible1']['svc_ansible_password'] }}"
  roles:
    - elk/elastic_stack_configure
