---

- name: "3.1.1 | PATCH | Ensure system is checked to determine if IPv6 is enabled"
  block:
      - name: "3.1.1 | PATCH | Ensure system is checked to determine if IPv6 is enabled | Add ipv6.disable if does not exist"
        ansible.builtin.lineinfile:
            path: /etc/default/grub
            regexp: '^(GRUB_CMDLINE_LINUX=.*)ipv6.disable=(0|1)(.*$)'
            line: '\g<1>\g<3> ipv6.disable=1'
            backrefs: true
        when: ubuntu22cis_ipv6_disable == 'grub'
        notify: Grub update

      - name: "3.1.1 | PATCH | Ensure system is checked to determine if IPv6 is enabled | Remove net.ipv6.conf.all.disable_ipv6"
        ansible.builtin.template:
            src: "{{ item }}.j2"
            dest: "/{{ item }}"
            owner: root
            group: root
            mode: 0640
        notify: Flush ipv6 route table
        loop:
            - etc/sysctl.d/60-disable_ipv6.conf
        when: ubuntu22cis_ipv6_disable == 'sysctl'
  when:
      - ubtu22cis_rule_3_1_1
      - not ubtu22cis_ipv6_required
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_3.1.1
      - ipv6

- name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  block:
      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Check for network-manager tool"
        ansible.builtin.shell: nmcli radio wifi
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_3_1_2_wifi_status
        when: "'network-manager' in ansible_facts.packages"

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Disable wireless if network-manager installed"
        ansible.builtin.shell: nmcli radio all off
        changed_when: ubtu22cis_3_1_2_nmcli_radio_off.rc == 0
        register: ubtu22cis_3_1_2_nmcli_radio_off
        when:
            - "'network-manager' in ansible_facts.packages"
            - "'enabled' in ubtu22cis_3_1_2_wifi_status.stdout"

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Warn about wireless if network-manager not installed"
        ansible.builtin.debug:
            msg: "Warning!! You need to disable wireless interfaces manually since network-manager is not installed"
        when: "'network-manager' not in ansible_facts.packages"

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Set warning count"
        ansible.builtin.import_tasks: warning_facts.yml
        when: "'network-manager' not in ansible_facts.packages"
  vars:
      warn_control_id: '3.1.2'
  when:
      - ubtu22cis_rule_3_1_2
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_3.1.2
      - wireless
