---

- name: Check OS version and family
  fail:
      msg: "This role can only be run against Amazon Linux 2. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - ansible_distribution != 'Amazon'
      - ansible_distribution_major_version is version_compare('2', '!=')
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.9 or greater
  when: not ansible_version.full is version_compare('2.9', '>=')
  tags:
      - always

- name: "check sugroup exists if used"
  block:
      - name: "Check su group exists if defined"
        command: grep -w "{{ amazon2cis_sugroup }}" /etc/group
        changed_when: false
        failed_when: sugroup_exists.rc >= 2
        register: sugroup_exists
        tags:
            - skip_ansible_lint

      - name: Check sugroup if defined exists before continuing
        assert:
            that: sugroup_exists.rc == 0
            msg: "The variable amazon2cis_sugroup is defined but does not exist please rectify"
  when:
      - amazon2cis_sugroup is defined
      - amazon2cis_rule_5_7
  tags:
      - rule_5.7

- include_tasks: check_prereqs.yml
  tags:
      - always
      - prereqs

- include_tasks: prelim.yml
  tags:
      - prelim_tasks
      - always

- import_tasks: pre_remediation_audit.yml
  when:
      - run_audit
  tags:
      - run_audit

- name: Gather the package facts
  package_facts:
      manager: auto
  tags:
      - always

- include_tasks: section_1/main.yml
  when: amazon2cis_section1
  tags:
      - amazon2cis_section1

- include_tasks: section_2/main.yml
  when: amazon2cis_section2
  tags:
      - amazon2cis_section2

- include_tasks: section_3/main.yml
  when: amazon2cis_section3
  tags:
      - amazon2cis_section3

- include_tasks: section_4/main.yml
  when: amazon2cis_section4
  tags:
      - amazon2cis_section4

- include_tasks: section_5/main.yml
  when: amazon2cis_section5
  tags:
      - amazon2cis_section5

- include_tasks: section_6/main.yml
  when: amazon2cis_section6
  tags:
      - amazon2cis_section6

# - include_tasks: post.yml
#   tags:
#   - post_tasks
#   - always

- name: flush handlers
  meta: flush_handlers

- name: run post_remediation audit
  import_tasks: post_remediation_audit.yml
  when:
      - run_audit
  tags:
      - run_audit

- name: Show Audit Summary
  debug:
      msg: "{{ audit_results.split('\n') }}"
  when:
      - run_audit
  tags:
      - run_audit
