---
- name: "PRELIM | Parse Password Entries | Parse /etc/passwd"
  block:
      - name: "PRELIM | Parse /etc/passwd"
        command: cat /etc/passwd
        changed_when: false
        failed_when: false
        check_mode: false
        register: amazon2cis_passwd_file_audit

      - name: "PRELIM | Parse Password EntriesSplit passwd entries"
        set_fact:
            amazon2cis_passwd: "{{ amazon2cis_passwd_file_audit.stdout_lines | map('regex_replace', ld_passwd_regex, ld_passwd_yaml) | map('from_yaml') | list }}"
        with_items:
            - "{{ amazon2cis_passwd_file_audit.stdout_lines }}"
        vars:
            ld_passwd_regex: >-
                ^(?P<id>[^:]*):(?P<password>[^:]*):(?P<uid>[^:]*):(?P<gid>[^:]*):(?P<gecos>[^:]*):(?P<dir>[^:]*):(?P<shell>[^:]*)
            ld_passwd_yaml: |
                id: >-4
                    \g<id>
                password: >-4
                    \g<password>
                uid: \g<uid>
                gid: \g<gid>
                gecos: >-4
                    \g<gecos>
                dir: >-4
                    \g<dir>
                shell: >-4
                    \g<shell>
  tags:
      - always
