---

- name: "4.2.1.1 | PATCH | Ensure rsyslog is installed"
  package:
      name: rsyslog
      state: present
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amazon2cis_rule_4_2_1_1
  tags:
      - level1
      - automated
      - patch
      - rule_4.2.1.1
      - rsyslog

- name: "4.2.1.2 | PATCH | Ensure rsyslog Service is enabled and running"
  service:
      name: rsyslog
      state: started
      enabled: true
  when:
      - amazon2cis_rule_4_2_1_2
  tags:
      - level1
      - automated
      - patch
      - rule_4.2.1.2
      - rsyslog

- name: "4.2.1.3 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'
  notify: restart rsyslog
  when:
      - amazon2cis_rule_4_2_1_3
  tags:
      - level1
      - automated
      - patch
      - rule_4.2.1.3
      - rsyslog

- name: "4.2.1.4 | PATCH | Ensure logging is configured"
  block:
      - name: "4.2.1.4 | AUDIT | Ensure logging is configured | rsyslog current config message out"
        command: cat /etc/rsyslog.conf
        changed_when: false
        failed_when: false
        register: amazon2_4_2_1_4_audit

      - name: "4.2.1.4 | PATCH | Ensure logging is configured | Debug out rsyslog settings"
        debug:
            msg:
                - "These are the current logging configurations for rsyslog, please review:"
                - "{{ amazon2_4_2_1_4_audit.stdout_lines }}"
        when: not amazon2cis_rsyslog_ansibleManaged

      - name: "4.2.1.4 | PATCH | Ensure logging is configured | Set logging settings lineinfile"
        lineinfile:
            path: /etc/rsyslog.conf
            state: present
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: '^[# ]*{{ item.insertafter }}\s*=\s*'
        with_items:
            - { regexp: '^\*\.emerge(.*)$', line: '*.emerg                                                  :omusrmsg:*', insertafter: '# Everybody gets emergency messages' }
            - { regexp: '^auth,authpriv\.\*', line: 'auth,authpriv.*                                          /var/log/secure', insertafter: '# The authpriv file has restricted access.' }
            - { regexp: '^mail\.\*(.*)$', line: 'mail.*                                                  -/var/log/mail', insertafter: '# Log all the mail messages in one place.' }
            - { regexp: '^mail.info(.*)$', line: 'mail.info                                               -/var/log/mail.info', insertafter: '# Log all the mail messages in one place.' }
            - { regexp: '^mail.warning(.*)$', line: 'mail.warning                                            -/var/log/mail.warning', insertafter: '# Log all the mail messages in one place.' }
            - { regexp: '^mail.err(.*)$', line: 'mail.err                                                /var/log/mail.err', insertafter: '# Log all the mail messages in one place.' }
            - { regexp: '^news.crit(.*)$', line: 'news.crit                                               -/var/log/news/news.crit', insertafter: '# Save news errors of level crit and higher in a special file.' }
            - { regexp: '^news.err(.*)$', line: 'news.err                                                -/var/log/news/news.crit', insertafter: '# Save news errors of level crit and higher in a special file.' }
            - { regexp: '^news.notice(.*)$', line: 'news.notice                                             -/var/log/news/news.crit', insertafter: '# Save news errors of level crit and higher in a special file.' }
        loop_control:
            label: "{{ item.line }}"
        notify: restart rsyslog
        when: amazon2cis_rsyslog_ansibleManaged

      - name: "4.2.1.4 | PATCH | Ensure logging is configured | Misc. log setting"
        blockinfile:
            path: /etc/rsyslog.conf
            state: present
            marker: "# {mark} MISC. LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
                # misc. logging additions to meet CIS standards
                *.=warning;*.=err                                        -/var/log/warn
                *.crit                                                   /var/log/warn
                *.*;mail.none;news.none                                  /var/log/messages
            insertafter: '#### RULES ####'
        notify: restart rsyslog
        when: amazon2cis_rsyslog_ansibleManaged

      - name: "4.2.1.4 | PATCH | Ensure logging is configured | Local log settings"
        blockinfile:
            path: /etc/rsyslog.conf
            state: present
            marker: "#{mark} LOCAL LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
                # local log settings
                local0,local1.*                                          -/var/log/localmessages
                local2,local3.*                                          -/var/log/localmessages
                local4,local5.*                                          -/var/log/localmessages
                local6,local7.*                                          -/var/log/localmessages
            insertafter: '#### RULES ####'
        notify: restart rsyslog
  when:
      - amazon2cis_rule_4_2_1_4
  tags:
      - level1
      - manual
      - patch
      - rule_4.2.1.4
      - rsyslog

- name: "4.2.1.5 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  blockinfile:
      path: /etc/rsyslog.conf
      state: present
      block: |
        # remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
        *.* @@{{ amazon2cis_remote_log_server }}
      insertafter: EOF
  failed_when:
      - amazon2cis_4_2_1_5_result is failed
      - amazon2cis_4_2_1_5_result.rc != 257
  register: amazon2cis_4_2_1_5_result
  notify: restart rsyslog
  when:
      - amazon2cis_rule_4_2_1_5
      - amazon2cis_remote_log_server is defined
  tags:
      - level1
      - automated
      - patch
      - rule_4.2.1.5
      - rsyslog

- name: "4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  block:
      - name: "4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | When not log host"
        replace:
            path: /etc/rsyslog.conf
            regexp: '({{ item }})'
            replace: '#\1'
        with_items:
            - '^(\$ModLoad imtcp)'
            - '^(\$InputTCPServerRun)'
        notify: restart rsyslog
        when:
            - not amazon2cis_system_is_log_server

      - name: "4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | When log host"
        replace:
            path: /etc/rsyslog.conf
            regexp: '^#(.*{{ item }}.*)'
            replace: '\1'
        with_items:
            - 'ModLoad imtcp'
            - 'InputTCPServerRun'
        notify: restart rsyslog
        when:
            - amazon2cis_system_is_log_server
  when:
      - amazon2cis_rule_4_2_1_6
  tags:
      - level1
      - patch
      - manual
      - rule_4.2.1.6
      - rsyslog

# - name: "MANUAL | 4.2.3 | AUDIT | Ensure logrotate is configured"
#   find:
#     paths: /etc/logrotate.d/
#   register: log_rotates
#   tags:
#   - level1
#   - audit
#   - manual
#   - rule_4.2.3

# - name: "AUTOMATED | 4.2.4 | PATCH | Ensure permissions on all logfiles are configured"
#   command: find /var/log -type f -exec chmod g-wx,o-rwx "{}" + -o -type d -exec chmod g-wx,o-rwx "{}" +
#   changed_when: no
#   failed_when: no
#   when:
#   - amazon2cis_rule_4_2_3
#   tags:
#   - level1
#   - patch
#   - automated
#   - rule_4.2.4
