---

- name: "1.6.1.1 | PATCH | Ensure SELinux is installed"
  package:
      name: libselinux
      state: present
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - not amazon2cis_selinux_disable
      - amazon2cis_rule_1_6_1_1
  tags:
      - level1
      - automated
      - patch
      - rule_1.6.1.1
      - selinux

- name: "1.6.1.2 | PATCH | Ensure SELinux is not disabled in bootloader configuration"
  replace:
      dest: /etc/default/grub
      regexp: '(selinux|enforcing)\s*=\s*0\s*'
  ignore_errors: true
  notify: grub2cfg
  when:
      - not amazon2cis_selinux_disable
      - amazon2cis_rule_1_6_1_2
  tags:
      - level1
      - automated
      - patch
      - rule_1.6.1.2
      - selinux

- name: |
    "1.6.1.3 | PATCH | Ensure SELinux policy is configured
     1.6.1.4 | PATCH | Ensure the SELinux state is enforcing or permissive"
  selinux:
      conf: /etc/selinux/config
      policy: "{{ amazon2cis_selinux_pol }}"
      state: "{{ amazon2cis_selinux_state }}"
  vars:
      ansible_python_interpreter: "{{ python2_bin }}"
  when:
      - not amazon2cis_selinux_disable
      - amazon2cis_rule_1_6_1_3
      - amazon2cis_rule_1_6_1_4
  tags:
      - level1
      - automated
      - patch
      - rule_1.6.1.3
      - rule_1.6.1.4
      - selinux

- name: "1.6.1.5 | PATCH | Ensure the SELinux state is enforcing"
  selinux:
      conf: /etc/selinux/config
      policy: "{{ amazon2cis_selinux_pol }}"
      state: enforcing
  vars:
      ansible_python_interpreter: "{{ python2_bin }}"
  when:
      - not amazon2cis_selinux_disable
      - not amazon2cis_selinux_state == "permissive"
      - amazon2cis_rule_1_6_1_5
  tags:
      - level2
      - automated
      - patch
      - rule_1.6.1.5
      - selinux

- name: "1.6.1.6 | AUDIT | Ensure no unconfined services exist"
  block:
      - name: "1.6.1.6 | AUDIT | Ensure no unconfined services exist | Find the unconfined services"
        shell: ps -eZ | grep unconfined_service_t
        changed_when: false
        failed_when: false
        register: amazon2cis_1_6_1_6_unconf_services

      - name: "1.6.1.6 | AUDIT | Ensure no unconfined services exist | Message on no unconfined services"
        debug:
            msg: "Good News! There are no unconfined services found on your system"
        when: amazon2cis_1_6_1_6_unconf_services.stdout | length == 0

      - name: "1.6.1.6 | AUDIT | Ensure no unconfined services exist | Message on unconfined services"
        debug:
            msg: "Warning! You have unconfined services: {{ amazon2cis_1_6_1_6_unconf_services.stdout_lines }}"
        when: amazon2cis_1_6_1_6_unconf_services.stdout | length > 0
  when:
      - amazon2cis_rule_1_6_1_6
  tags:
      - level1
      - automated
      - audit
      - rule_1.6.1.6
      - selinux

- name: "1.6.1.7 | PATCH | Ensure SETroubleshoot is not installed"
  package:
      name: setroubleshoot
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amazon2cis_rule_1_6_1_7
  tags:
      - level1
      - automated
      - patch
      - rule_1.6.1.7
      - selinux

- name: "1.6.1.8 | PATCH | Ensure the MCS Translation Service (mcstrans) is not installed"
  package:
      name: mcstrans
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amazon2cis_rule_1_6_1_8
  tags:
      - level1
      - automated
      - patch
      - rule_1.6.1.8
      - mcstrans
