---
- name: "AUTOMATED | 2.1.1.1 | PATCH | Ensure time synchronization is in use"
  apt:
      name: "{{ ubtu18cis_time_sync_tool }}"
      state: present
  when:
      - ubtu18cis_rule_2_1_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.1.1
      - chrony

- name: "MANUAL | 2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured"
  block:
      - name: "MANUAL | 2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured | Set configuration for systemd-timesyncd"
        lineinfile:
            path: /etc/systemd/timesyncd.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: "{{ item.insertafter }}"
        with_items:
            - { regexp: '^\[Time\]', line: '[Time]', insertafter: EOF }
            - { regexp: '^#NTP|^NTP', line: 'NTP=0.ubuntu.pool.ntp.org 1.ubuntu.pool.ntp.org 2.ubuntu.pool.ntp.org', insertafter: '\[Time\]' }
            - { regexp: '^#FallbackNTP|^FallbackNTP', line: 'FallbackNTP=ntp.ubuntu.com 3.ubuntu.pool.ntp.org', insertafter: '\[Time\]' }
            - { regexp: '^#RootDistanceMaxSec|^RootDistanceMaxSec', line: 'RootDistanceMaxSec=1', insertafter: '\[Time\]'}

      - name: "MANUAL | 2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured | Start and enable the systemd-timesyncd service"
        service:
            name: systemd-timesyncd.service
            state: started
            enabled: true

      - name: "MANUAL | 2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured | Set timedatectl to ntp"
        command: timedatectl set-ntp true
  when:
      - ubtu18cis_rule_2_1_1_2
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_2.1.1.2
      - systemd-timesyncd

- name: "AUTOMATED | 2.1.1.3 | PATCH | Ensure chrony is configured"
  block:
      - name: "AUTOMATED | 2.1.1.3 | AUDIT | Ensure chrony is configured | Check for chrony user"
        shell: grep chrony /etc/passwd
        changed_when: false
        failed_when: false
        register: ubtu18cis_2_1_1_3_chrony_user_status

      - name: "AUTOMATED | 2.1.1.3 | PATCH | Ensure chrony is configured | Set chrony.conf file"
        template:
            src: chrony.conf.j2
            dest: /etc/chrony/chrony.conf
            owner: root
            group: root
            mode: 0644

      - name: "AUTOMATED | 2.1.1.3 | PATCH | Ensure chrony is configured | Create chrony user"
        user:
            name: chrony
            shell: /usr/sbin/nologin
            system: true
        when: ubtu18cis_2_1_1_3_chrony_user_status.stdout | length > 0

      - name: "AUTOMATED | 2.1.1.3 | PATCH | Ensure chrony is configured | Set option to use chrony user"
        lineinfile:
            path: /etc/default/chrony
            regexp: '^DAEMON_OPTS'
            line: 'DAEMON_OPTS="-u chrony"'
  when:
      - ubtu18cis_rule_2_1_1_3
      - ubtu18cis_time_sync_tool == "chrony"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.1.3
      - chrony

- name: "AUTOMATED | 2.1.1.4 | PATCH | Ensure ntp is configured"
  block:
      - name: "AUTOMATED | 2.1.1.4 | PATCH | Ensure ntp is configured | Set ntp.conf settings"
        template:
            src: ntp.conf.j2
            dest: /etc/ntp.conf
            owner: root
            group: root
            mode: 0644

      - name: "AUTOMATED | 2.1.1.4 | PATCH | Ensure ntp is configured | Modify sysconfig/ntpd"
        lineinfile:
            path: /etc/sysconfig/ntpd
            regexp: "{{ item.regexp }}"
            line: "{{ item. line }}"
            create: true
        with_items:
            - { regexp: '^OPTIONS', line: 'OPTIONS="-u ntp:ntp"'}
            - { regexp: '^NTPD_OPTIONS', line: 'NTPD_OPTIONS="-u ntp:ntp"' }

      - name: "AUTOMATED | 2.1.1.4 | PATCH | Ensure ntp is configured | Modify /etc/init.d/npt"
        lineinfile:
            path: /etc/init.d/ntp
            regexp: '^RUNAUSER'
            line: 'RUNAUSER=npt'
  when:
      - ubtu18cis_rule_2_1_1_4
      - ubtu18cis_time_sync_tool == "ntp"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.1.4
      - ntp

- name: "AUTOMATED | 2.1.2 | PATCH | Ensure X Window System is not installed"
  apt:
      name: xserver-xorg*
      state: absent
  when:
      - ubtu18cis_rule_2_1_2
      - not ubtu18cis_desktop_required
  tags:
      - level1-server
      - automated
      - patch
      - rule_2.1.2
      - xwindows

- name: "AUTOMATED | 2.1.3 | PATCH | Ensure Avahi Server is not installed"
  block:
      - name: "AUTOMATED | 2.1.3 | PATCH | Ensure Avahi Server is not installed | Stop and disable Avahi service"
        service:
            name: avahi-daemon
            state: stopped
            enabled: false
        when: avahi_service_status.stdout == "loaded"

      - name: "AUTOMATED | 2.1.3 | PATCH | Ensure Avahi Server is not installed | Uninstall Avahi service"
        apt:
            name: avahi-daemon
            state: absent
  when:
      - ubtu18cis_rule_2_1_3
      - not ubtu18cis_avahi_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.3
      - avahi
      - services

- name: "AUTOMATED | 2.1.4 | PATCH | Ensure CUPS is not installed"
  apt:
      name: cups
      state: absent
  when:
      - ubtu18cis_rule_2_1_4
      - not ubtu18cis_cups_server
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_2.1.4
      - cups
      - services

- name: "AUTOMATED | 2.1.5 | PATCH | Ensure DHCP Server is not installed"
  apt:
      name: isc-dhcp-server
      state: absent
  when:
      - ubtu18cis_rule_2_1_5
      - not ubtu18cis_dhcp_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.5
      - dhcp
      - services

- name: "AUTOMATED | 2.1.6 | PATCH | Ensure LDAP server is not installed"
  apt:
      name: slapd
      state: absent
  when:
      - ubtu18cis_rule_2_1_6
      - not ubtu18cis_ldap_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.6
      - ldap
      - services

- name: "AUTOMATED | 2.1.7 | PATCH | Ensure NFS is not installed"
  apt:
      name: nfs-kernel-server
      state: absent
  when:
      - ubtu18cis_rule_2_1_7
      - not ubtu18cis_nfs_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.7
      - nfs
      - services

- name: "AUTOMATED | 2.1.8 | PATCH | Ensure DNS Server is not installed"
  apt:
      name: bind9
      state: absent
  when:
      - ubtu18cis_rule_2_1_8
      - not ubtu18cis_dns_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.8
      - dns
      - service

- name: "AUTOMATED | 2.1.9 | PATCH | Ensure FTP Server is not installed"
  apt:
      name: vsftpd
      state: absent
  when:
      - ubtu18cis_rule_2_1_9
      - not ubtu18cis_vsftpd_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.9
      - ftp
      - service

- name: "AUTOMATED | 2.1.10 | PATCH | Ensure HTTP server is not installed"
  apt:
      name: apache2
      state: absent
  when:
      - ubtu18cis_rule_2_1_10
      - not ubtu18cis_httpd_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.10
      - httpd
      - service

- name: "AUTOMATED | 2.1.11 | PATCH | Ensure IMAP and POP3 server are not installed"
  apt:
      name: ['dovecot-imapd', 'dovecot-pop3d']
      state: absent
  when:
      - ubtu18cis_rule_2_1_11
      - not ubtu18cis_dovecot_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.11
      - dovecot
      - service

- name: "AUTOMATED | 2.1.12 | PATCH | Ensure Samba is not installed"
  apt:
      name: samba
      state: absent
  when:
      - ubtu18cis_rule_2_1_12
      - not ubtu18cis_smb_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.12
      - samba
      - service

- name: "AUTOMATED | 2.1.13 | PATCH | Ensure HTTP Proxy Server is not installed"
  apt:
      name: squid
      state: absent
  when:
      - ubtu18cis_rule_2_1_13
      - not ubtu18cis_squid_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.13
      - http_proxy
      - service

- name: "AUTOMATED | 2.1.14 | PATCH | Ensure SNMP Server is not installed"
  apt:
      name: snmpd
      state: absent
  when:
      - ubtu18cis_rule_2_1_14
      - not ubtu18cis_snmp_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.14
      - snmp
      - service

- name: "AUTOMATED | 2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  block:
      - name: "AUTOMATED | 2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode | For postfix"
        lineinfile:
            path: /etc/postfix/main.cf
            regexp: '^(#)?inet_interfaces'
            line: 'inet_interfaces = loopback-only'
        notify: restart postfix
        when: "'postfix' in ansible_facts.packages"

      - name: "AUTOMATED | 2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode | for exim4"
        lineinfile:
            path: /etc/exim4/update-exim4.conf.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
        notify: restart exim4
        with_items:
            - { regexp: '^dc_eximconfig_configtype=', line: dc_eximconfig_configtype='local' }
            - { regexp: '^dc_local_interfaces=', line: "dc_local_interfaces='127.0.0.1 ; ::1'" }
            - { regexp: '^dc_readhost=', line: dc_readhost='' }
            - { regexp: '^dc_relay_domains=', line: dc_relay_domains='' }
            - { regexp: '^dc_minimaldns=', line: dc_minimaldns='false' }
            - { regexp: '^dc_relay_nets=', line: dc_relay_nets='' }
            - { regexp: '^dc_smarthost=', line: dc_smarthost='' }
            - { regexp: '^dc_use_split_config=', line: dc_use_split_config='false' }
            - { regexp: '^dc_hide_mailname=', line: dc_hide_mailname='' }
            - { regexp: '^dc_mailname_in_oh=', line: dc_mailname_in_oh='true' }
            - { regexp: '^dc_localdelivery=', line: dc_localdelivery='mail_spool' }
        when: "'exim4' in ansible_facts.packages"
  when:
      - ubtu18cis_rule_2_1_15
      - ubtu18cis_mail_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.15
      - postfix

- name: "AUTOMATED | 2.1.16 | PATCH | Ensure rsync service is not installed"
  apt:
      name: rsync
      state: absent
      purge: true
  when:
      - ubtu18cis_rule_2_1_16
      - not ubtu18cis_rsync_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.16
      - rsync

- name: "AUTOMATED | 2.1.17 | PATCH | Ensure NIS Server is not enabled"
  apt:
      name: nis
      state: absent
  when:
      - ubtu18cis_rule_2_1_17
      - not ubtu18cis_nis_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - rule_2.1.17
      - nis
      - service
