---
- hosts: 127.0.0.1
  become: true
  become_method: sudo
  connection: local
  gather_facts: true
  vars:
    ubtu20cis_rule_3_2_2: false # Coalfire Edit: Kubernetes requires IPV4 forwarding on worker nodes
  tasks:
    # Note: Using this method to generate random password hash due to issues using password_hash plugin
    - name: Generate random password
      ansible.builtin.command:
        cmd: "openssl passwd -6 '{{ lookup('ansible.builtin.password', '/dev/null') }}'"
      register: random_pass
      retries: 3
      until: random_pass is not failed
      changed_when: false
      no_log: true
      tags:
        - always

    - name: Set password variable
      ansible.builtin.set_fact:
        ubtu20cis_root_pw: "{{ random_pass.stdout }}"
      no_log: true
      tags:
        - always

    # Needed for EKS worker node
    - name: Enable IPv4 Forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true
        ignoreerrors: true
      tags:
        - always

    - name: Pass variables to role
      ansible.builtin.include_role:
        name: ubuntu20
      tags:
        - always
