---
- name: "AUTOMATED | 5.3.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
      path: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
  when:
      - ubtu18cis_rule_5_3_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.1
      - ssh

- name: "AUTOMATED | 5.3.2 | PATCH | Ensure permissions on SSH private host key files are configured"
  block:
      - name: "AUTOMATED | 5.3.2 | AUDIT | Ensure permissions on SSH private host key files are configured | Find ssh_host private keys"
        find:
            paths: /etc/ssh
            patterns: 'ssh_host_*_key'
        register: ubtu18cis_5_3_2_ssh_host_priv_keys

      - name: "AUTOMATED | 5.3.2 | PATCH | Ensure permissions on SSH private host key files are configured | Set permissions"
        file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: 0600
        with_items:
            - "{{ ubtu18cis_5_3_2_ssh_host_priv_keys.files }}"
  when:
      - ubtu18cis_rule_5_3_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.2
      - ssh

- name: "AUTOMATED | 5.3.3 | PATCH | Ensure permissions on SSH public host key files are configured"
  block:
      - name: "AUTOMATED | 5.3.3 | PATCH | Ensure permissions on SSH public host key files are configured | Find ssh_host public keys"
        find:
            paths: /etc/ssh
            patterns: 'ssh_host_*_key.pub'
        register: ubtu18cis_5_3_3_ssh_host_pub_keys

      - name: "AUTOMATED | 5.3.3 | PATCH | Ensure permissions on SSH public host key files are configured | Set permissions"
        file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: 0644
        with_items:
            - "{{ ubtu18cis_5_3_3_ssh_host_pub_keys.files }}"
  when:
      - ubtu18cis_rule_5_3_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.3
      - ssh

- name: "AUTOMATED | 5.3.4 | PATCH | Ensure SSH access is limited"
  block:
      - name: "AUTOMATED | 5.3.4 | PATCH | Ensure SSH access is limited | Add allowed users"
        lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^AllowUsers|^#AllowUsers'
            line: 'AllowUsers {{ ubtu18cis_sshd.allow_users }}'
        notify: restart sshd
        when: "ubtu18cis_sshd['allow_users']|default('') != ''"

      - name: "AUTOMATED | 5.3.4 | PATCH | Ensure SSH access is limited | Add allowed groups"
        lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^AllowGroups|^#AllowGroups'
            line: 'AllowGroups {{ ubtu18cis_sshd.allow_groups }}'
        notify: restart sshd
        when: "ubtu18cis_sshd['allow_groups']|default('') != ''"

      - name: "AUTOMATED | 5.3.4 | PATCH | Ensure SSH access is limited | Add deny users"
        lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^DenyUsers|^#DenyUsers'
            line: 'DenyUsers {{ ubtu18cis_sshd.deny_users }}'
        notify: restart sshd
        when: "ubtu18cis_sshd['deny_users']|default('') != ''"

      - name: "AUTOMATED | 5.3.4 | PATCH | Ensure SSH access is limited | Add deny groups"
        lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^DenyGroups|^#DenyGroups'
            line: 'DenyGroups {{ ubtu18cis_sshd.deny_groups }}'
        notify: restart sshd
        when: "ubtu18cis_sshd['deny_groups']|default('') != ''"
  when:
      - ubtu18cis_rule_5_3_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.4
      - ssh

- name: "AUTOMATED | 5.3.5 | PATCH | Ensure SSH LogLevel is appropriate"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^LogLevel|^#LogLevel'
      line: 'LogLevel {{ ubtu18cis_sshd.log_level }}'
      insertafter: '^# Logging'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.5
      - ssh

- name: "AUTOMATED | 5.3.6 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^X11Forwarding|^#X11Forwarding'
      line: 'X11Forwarding no'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_6
  tags:
      - level2-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.6
      - ssh

- name: "AUTOMATED | 5.3.7 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MaxAuthTries|^#MaxAuthTries'
      line: 'MaxAuthTries {{ ubtu18cis_sshd.max_auth_tries }}'
      insertafter: '^# Authentication'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.7
      - ssh

- name: "AUTOMATED | 5.3.8 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^IgnoreRhosts|^#IgnoreRhosts'
      line: 'IgnoreRhosts yes'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_8
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.8
      - ssh

- name: "AUTOMATED | 5.3.9 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^HostbasedAuthentication|^#HostbasedAuthentication'
      line: 'HostbasedAuthentication no'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_9
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.9
      - ssh

- name: "AUTOMATED | 5.3.10 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin|^#PermitRootLogin'
      line: 'PermitRootLogin no'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_10
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.10
      - ssh

- name: "AUTOMATED | 5.3.11 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords|^#PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
      insertafter: '# To disable tunneled clear text passwords'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_11
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_5.3.11
      - ssh

- name: "AUTOMATED | 5.3.12 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitUserEnvironment|^#PermitUserEnvironment'
      line: 'PermitUserEnvironment no'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_12
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.12
      - ssh

- name: "AUTOMATED | 5.3.13 | PATCH | Ensure only strong Ciphers are used"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Ciphers|^#Ciphers'
      line: 'Ciphers {{ ubtu18cis_sshd.ciphers }}'
      insertafter: '^# Ciphers and keying'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_13
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.13
      - ssh

- name: "AUTOMATED | 5.3.14 | PATCH | Ensure only strong MAC algorithms are used"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MACs|^#MACs'
      line: 'MACs {{ ubtu18cis_sshd.macs }}'
      insertafter: '^# Ciphers and keying'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_14
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.14
      - ssh

- name: "AUTOMATED | 5.3.15 | PATCH | Ensure only strong Key Exchange algorithms are used"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^KexAlgorithms|^#KexAlgorithms'
      line: 'KexAlgorithms {{ ubtu18cis_sshd.kex_algorithms }}'
      insertafter: '^# Ciphers and keying'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_15
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.15
      - ssh

- name: "AUTOMATED | 5.3.16 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  with_items:
      - { regexp: '^ClientAliveInterval|^#ClientAliveInterval', line: 'ClientAliveInterval {{ ubtu18cis_sshd.client_alive_interval }}' }
      - { regexp: '^ClientAliveCountMax|^#ClientAliveCountMax', line: 'ClientAliveCountMax {{ ubtu18cis_sshd.client_alive_count_max }}' }
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_16
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.16
      - sshd

- name: "AUTOMATED | 5.3.17 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^LoginGraceTime|^#LoginGraceTime'
      line: 'LoginGraceTime {{ ubtu18cis_sshd.login_grace_time }}'
      insertafter: '^# Authentication'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_17
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.17
      - ssh

- name: "AUTOMATED | 5.3.18 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Banner|^#Banner'
      line: Banner /etc/issue.net
      insertafter: '^# no default banner path'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_18
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.18
      - ssh

- name: "AUTOMATED | 5.3.19 | PATCH | Ensure SSH PAM is enabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^UsePAM|^#UsePAM'
      line: 'UsePAM yes'
      insertafter: '^# and ChallengeResponseAuthentication'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_19
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.19
      - ssh
      - pam

- name: "AUTOMATED | 5.3.20 | PATCH | Ensure SSH AllowTcpForwarding is disabled"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^AllowTcpForwarding|^#AllowTcpForwarding'
      line: 'AllowTcpForwarding no'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_20
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_5.3.20
      - ssh

- name: "AUTOMATED | 5.3.21 | PATCH | Ensure SSH MaxStartups is configured"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MaxStartups|^#MaxStartups'
      line: 'MaxStartups 10:30:60'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_21
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.21
      - ssh

- name: "AUTOMATED | 5.3.22 | PATCH | Ensure SSH MaxSessions is limited"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MaxSessions|^#MaxSessions'
      line: 'MaxSessions {{ ubtu18cis_sshd.max_sessions }}'
      insertafter: '^# Authentication'
  notify: restart sshd
  when:
      - ubtu18cis_rule_5_3_22
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.22
      - ssh
