---
- name: "MANUAL | 5.6 | AUDIT | Ensure root login is restricted to system console"
  block:
      - name: "MANUAL | 5.6 | AUDIT | Ensure root login is restricted to system console | Get list of all terminals"
        command: cat /etc/securetty
        changed_when: false
        failed_when: false
        register: ubtu18cis_5_6_terminal_list

      - name: "MANUAL | 5.6 | AUDIT | Ensure root login is restricted to system console | Message out list"
        debug:
            msg:
                - "Warning!! Below is the list of conoles with root login access"
                - "Please review for any conoles that are not in a physically secure location"
                - "{{ ubtu18cis_5_6_terminal_list.stdout_lines }}"

      - name: "MANUAL | 5.6 | AUDIT | Ensure root login is restricted to system console | Warn Count."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: '5.6'
  when:
      - ubtu18cis_rule_5_6
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_5.6
      - user
