---
# List users in order to look files inside each home directory
- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  changed_when: false
  register: ubtu18cis_users
  when:
      - ubtu18cis_rule_6_2_8 or
        ubtu18cis_rule_6_2_9 or
        ubtu18cis_rule_6_2_10

- name: "PRELIM | Check for autofs service"
  shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: ubtu18cis_autofs_service_status
  changed_when: false
  check_mode: false
  when:
      - ubtu18cis_rule_1_1_23
  tags:
      - skip_ansible_lint

# Commented out, don't know why it fails
#- name: "PRELIM | Run apt update"
#  apt:
#      update_cache: true
#  when:
#      - ubtu18cis_rule_1_3_1

- name: "PRELIM | Check for avahi-daemon service"
  shell: "systemctl show avahi-daemon | grep LoadState | cut -d = -f 2"
  register: avahi_service_status
  changed_when: false
  check_mode: false
  tags:
      - skip_ansible_lint

- name: "PRELIM | Install gdm3"
  apt:
      name: gdm3
      state: present
  when:
      - ubtu18cis_desktop_required
      - ubtu18cis_install_gdm3
      - ubtu18cis_rule_1_8_2 or
        ubtu18cis_rule_1_8_3

- name: "PRELIM | Install nftables"
  apt:
      name: nftables
      state: present
  when: ubtu18cis_firewall_package == "nftables"
