---

- name: "2.1.1.1 | PATCH | Ensure time synchronization is in use"
  block:
      - name: "2.1.1.1 | PATCH | Ensure time synchronization is in use | service install"
        package:
            name: "{{ amazon2cis_time_synchronization }}"
            state: present
        vars:
            ansible_python_interpreter: /bin/python

      - name: "2.1.1.1 | PATCH | Ensure time synchronization is in use | service start"
        service:
            name: "{{ amazon2cis_time_synchronization }}d"
            state: started
            enabled: true

      - name: "2.1.1.1 | PATCH | Ensure time synchronization is in use | service stop ntp"
        service:
            name: ntpd
            state: stopped
            enabled: false
        when:
            - "'ntp' in ansible_facts.packages"
            - amazon2cis_time_synchronization == "chrony"

      - name: "2.1.1.1 | PATCH | Ensure time synchronization is in use | service stop chrony"
        service:
            name: chronyds
        when:
            - "'chrony' in ansible_facts.packages"
            - amazon2cis_time_synchronization == "ntp"
  when:
      - amazon2cis_rule_2_1_1_1
      - not amazon2cis_system_is_container
  tags:
      - level1
      - automated
      - patch
      - rule_2.1.1.1
      - ntps

- name: "2.1.1.2 | PATCH | Ensure chrony is configured"
  block:
      - name: "2.1.1.2 | PATCH | Ensure chrony is configured | modify /etc/chrony.conf"
        template:
            src: chrony.conf.j2
            dest: /etc/chrony.conf
            owner: root
            group: root
            mode: 0644

      - name: "2.1.1.2 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd"
        lineinfile:
            dest: /etc/sysconfig/chronyd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u chrony\""
            state: present
            owner: root
            group: root
            mode: 0640
            create: true
  when:
      - amazon2cis_rule_2_1_1_2
      - amazon2cis_time_synchronization == "chrony"
      - not amazon2cis_system_is_container
  tags:
      - level1
      - automated
      - patch
      - rule_2.1.1.2
      - ntp

- name: "2.1.1.3 | PATCH | Ensure ntp is configured"
  block:
      - name: "2.1.1.3 | PATCH | Ensure ntp is configured | modify /etc/ntp.conf"
        template:
            src: ntp.conf.j2
            dest: /etc/ntp.conf
            owner: root
            group: root
            mode: 0644

      - name: "2.1.1.3 | PATCH | Ensure ntp is configured | modify /etc/sysconfig/ntpd"
        lineinfile:
            dest: /etc/sysconfig/ntpd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u ntp:ntp\""
        notify: systemd daemon reloads

      - name: "2.1.1.3 | PATCH | Ensure ntp is configured | modify /usr/lib/systemd/system/ntpd.service"
        lineinfile:
            dest: /usr/lib/systemd/system/ntpd.service
            regexp: "^(#)?ExecStart"
            line: "ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS"
        notify: systemd daemon reload
  when:
      - amazon2cis_rule_2_1_1_3
      - amazon2cis_time_synchronization == "ntp"
      - not amazon2cis_system_is_container
  tags:
      - level1
      - automated
      - patch
      - rule_2.1.1.3
      - ntp
