---

- name: "2.2.1 | PATCH | Ensure nis client is not installed"
  package:
      name: ypbind
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - not amazon2cis_ypbind_required
      - "'ypbind' in ansible_facts.packages"
      - amazon2cis_rule_2_2_1
  tags:
      - level1
      - automated
      - patch
      - rule_2.2.1
      - nis

- name: "2.2.2 | PATCH | Ensure rsh client is not installed"
  package:
      name: rsh
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - not amazon2cis_rsh_required
      - "'rsh' in ansible_facts.packages"
      - amazon2cis_rule_2_2_2
  tags:
      - level1
      - automated
      - patch
      - rule_2.2.2
      - rsh

- name: "2.2.3 | PATCH | Ensure talk client is not installed"
  package:
      name: talk
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - not amazon2cis_talk_required
      - "'talk' in ansible_facts.packages"
      - amazon2cis_rule_2_2_3
  tags:
      - level1
      - automated
      - patch
      - rule_2.2.3
      - talk

- name: "2.2.4 | PATCH | Ensure telnet client is not installed"
  package:
      name: telnet
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - "'telnet' in ansible_facts.packages"
      - not amazon2cis_telnet_required
      - amazon2cis_rule_2_2_4
  tags:
      - level1
      - automated
      - patch
      - rule_2.2.4
      - telnet

- name: "2.2.5 | PATCH | Ensure LDAP client is not installed"
  package:
      name: openldap-client
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - not amazon2cis_openldap_clients_required
      - "'openldap-client' in ansible_facts.packages"
      - amazon2cis_rule_2_2_5
  tags:
      - level1
      - automated
      - patch
      - rule_2.2.5
      - ldap_client
