---

- name: "SECTION | 1.1.1 | Disable Unused Filesystems"
  ansible.builtin.import_tasks: cis_1.1.1.x.yml

- name: "SECTION | 1.1.2 | configure /tmp"
  ansible.builtin.import_tasks: cis_1.1.2.x.yml

- name: "SECTION | 1.1.3 | configure /var"
  ansible.builtin.import_tasks: cis_1.1.3.x.yml

- name: "SECTION | 1.1.4 | configure /var/tmp"
  ansible.builtin.import_tasks: cis_1.1.4.x.yml

- name: "SECTION | 1.1.5 | configure /var/log"
  ansible.builtin.import_tasks: cis_1.1.5.x.yml

- name: "SECTION | 1.1.6 | configure /var/log/audit"
  ansible.builtin.import_tasks: cis_1.1.6.x.yml

- name: "SECTION | 1.1.7 | configure /home"
  ansible.builtin.import_tasks: cis_1.1.7.x.yml

- name: "SECTION | 1.1.8 | configure /dev/shm"
  ansible.builtin.import_tasks: cis_1.1.8.x.yml

- name: "SECTION | 1.1.9 | configure software updates"
  ansible.builtin.import_tasks: cis_1.1.9.yml

- name: "SECTION | 1.1.10 | Disable USB storage"
  ansible.builtin.import_tasks: cis_1.1.10.yml

- name: "SECTION | 1.2 | Configure Software Updates"
  ansible.builtin.import_tasks: cis_1.2.x.yml

- name: "SECTION | 1.3. | Filesystem Integrity Checking"
  ansible.builtin.import_tasks: cis_1.3.x.yml

- name: "SECTION | 1.4 | Secure Boot Settings"
  ansible.builtin.import_tasks: cis_1.4.x.yml

- name: "SECTION | 1.5 | Additional Process Hardening"
  ansible.builtin.import_tasks: cis_1.5.x.yml

- name: "SECTION | 1.6 | Mandatory Access Control"
  ansible.builtin.import_tasks: cis_1.6.x.yml

- name: "SECTION | 1.7 | Command Line Warning Banners"
  ansible.builtin.import_tasks: cis_1.7.x.yml

- name: "SECTION | 1.8 | GNOME Display Manager"
  ansible.builtin.import_tasks: cis_1.8.x.yml
  when: "'gdm3' in ansible_facts.packages"

- name: "SECTION | 1.9 | Ensure updates, patches, and additional security software are installed"
  ansible.builtin.import_tasks: cis_1.9.yml
